services:
  my-postgres:
    image: postgres:latest
    platform: linux/amd64
    env_file:
      - .env.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql  # Updated path to init.sql
    ports:
      - '5433:5432'

volumes:
  postgres_data:
